#ifndef TESTS_SERVICE_COMPONENTS_H
#define TESTS_SERVICE_COMPONENTS_H

/******************************************************************************
 * This file has been automatically generated by jack-make
 ******************************************************************************/

#if defined(JACK_WITH_SIM)
/******************************************************************************
 * The JACK services as component for integration with the simulator
 ******************************************************************************/
#include <sim/components/service.h>


/******************************************************************************
 * The JACK services as component for integration with the simulator
 ******************************************************************************/

#endif /// defined(JACK_WITH_SIM)
#endif /// TESTS_SERVICE_COMPONENTS_H