#ifndef TESTS_EVENTS_H
#define TESTS_EVENTS_H

/******************************************************************************
 * This file has been automatically generated by jack-make
 ******************************************************************************/

/// tests

/// Sim
#include <sim/simevent.h>
#include <sim/sim.h>

/// JACK
#include <jack/handles.h>

/// Third Party
#include <nlohmann/json.hpp>
#include <string>
#include <string_view>



#endif /// TESTS_EVENTS_H