cmake_minimum_required(VERSION 3.22.1)

# This file is automatically generated by jack-make and generates CMake
# target and variables for the JACK project that includes the file.
#
# Project: tests
#
# Options
# - JACK_MAKE_GENERATED_HEADERS_TESTS
#   CMake variable containing the list of header files that were generated.
#
# - JACK_MAKE_GENERATED_SOURCES_TESTS
#   CMake variable containing the list of source files that were generated.
#
# - JACK_MAKE_GENERATED_INCLUDE_DIRS_TESTS
#   CMake variable containing the include directories for the project

# Options
# Variables
set(JACK_MAKE_GENERATED_HEADERS_TESTS
    # Project
    ${CMAKE_CURRENT_LIST_DIR}/../meta/testsproject.h

    # Beliefsets
    ${CMAKE_CURRENT_LIST_DIR}/../meta/messages/pingmeta.h
    ${CMAKE_CURRENT_LIST_DIR}/../meta/messages/pongmeta.h
    ${CMAKE_CURRENT_LIST_DIR}/../meta/messages/pingpongbeliefsetmeta.h
    ${CMAKE_CURRENT_LIST_DIR}/../meta/messages/agentplanswitchmeta.h
    ${CMAKE_CURRENT_LIST_DIR}/../meta/messages/dummyflagmeta.h

    # Agents

    # Teams

    # Goals

    # Plans

    # Services

    # Other
    ${CMAKE_CURRENT_LIST_DIR}/../meta/testsenumsmeta.h
    ${CMAKE_CURRENT_LIST_DIR}/../meta/testsservicecomponents.h
)

set(JACK_MAKE_GENERATED_SOURCES_TESTS
    ${CMAKE_CURRENT_LIST_DIR}/../meta/testsproject.cpp

    # Beliefsets
    ${CMAKE_CURRENT_LIST_DIR}/../meta/messages/pingmeta.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../meta/messages/pongmeta.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../meta/messages/pingpongbeliefsetmeta.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../meta/messages/agentplanswitchmeta.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../meta/messages/dummyflagmeta.cpp

    # Agents

    # Teams

    # Goals

    # Plans

    # Services

    # Enums
    ${CMAKE_CURRENT_LIST_DIR}/../meta/testsenumsmeta.cpp
)

set(JACK_MAKE_GENERATED_INCLUDE_DIRS_TESTS ${CMAKE_CURRENT_LIST_DIR}/../..)