cmake_minimum_required(VERSION 3.22.1)

# This file is automatically generated by jack-make and generates CMake
# target and variables for the JACK project that includes the file.
#
# Project: gol
#
# Options
# - JACK_MAKE_GENERATED_HEADERS_GOL
#   CMake variable containing the list of header files that were generated.
#
# - JACK_MAKE_GENERATED_SOURCES_GOL
#   CMake variable containing the list of source files that were generated.
#
# - JACK_MAKE_GENERATED_INCLUDE_DIRS_GOL
#   CMake variable containing the include directories for the project

# Options
# Variables
set(JACK_MAKE_GENERATED_HEADERS_GOL
    # Project
    ${CMAKE_CURRENT_LIST_DIR}/../meta/golproject.h

    # Beliefsets
    ${CMAKE_CURRENT_LIST_DIR}/../meta/messages/cellcommandmeta.h
    ${CMAKE_CURRENT_LIST_DIR}/../meta/messages/cellinfometa.h

    # Agents
    ${CMAKE_CURRENT_LIST_DIR}/../impl/agents/gameoflifeagentimpl.h
    ${CMAKE_CURRENT_LIST_DIR}/../meta/agents/gameoflifeagentmeta.h

    # Teams

    # Goals
    ${CMAKE_CURRENT_LIST_DIR}/../impl/goals/modellifeimpl.h
    ${CMAKE_CURRENT_LIST_DIR}/../meta/goals/modellifemeta.h

    # Plans
    ${CMAKE_CURRENT_LIST_DIR}/../meta/plans/liveplanmeta.h
    ${CMAKE_CURRENT_LIST_DIR}/../impl/plans/liveplanimpl.h
    ${CMAKE_CURRENT_LIST_DIR}/../meta/plans/dieplanmeta.h
    ${CMAKE_CURRENT_LIST_DIR}/../impl/plans/dieplanimpl.h

    # Services
    ${CMAKE_CURRENT_LIST_DIR}/../impl/services/gameoflifeserviceimpl.h
    ${CMAKE_CURRENT_LIST_DIR}/../meta/services/gameoflifeservicemeta.h

    # Other
    ${CMAKE_CURRENT_LIST_DIR}/../meta/golenumsmeta.h
    ${CMAKE_CURRENT_LIST_DIR}/../meta/golservicecomponents.h
)

set(JACK_MAKE_GENERATED_SOURCES_GOL
    ${CMAKE_CURRENT_LIST_DIR}/../meta/golproject.cpp

    # Beliefsets
    ${CMAKE_CURRENT_LIST_DIR}/../meta/messages/cellcommandmeta.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../meta/messages/cellinfometa.cpp

    # Agents
    ${CMAKE_CURRENT_LIST_DIR}/../impl/agents/gameoflifeagentimpl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../meta/agents/gameoflifeagentmeta.cpp

    # Teams

    # Goals
    ${CMAKE_CURRENT_LIST_DIR}/../meta/goals/modellifemeta.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../impl/goals/modellifeimpl.cpp

    # Plans
    ${CMAKE_CURRENT_LIST_DIR}/../meta/plans/liveplanmeta.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../impl/plans/liveplanimpl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../meta/plans/dieplanmeta.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../impl/plans/dieplanimpl.cpp

    # Services
    ${CMAKE_CURRENT_LIST_DIR}/../impl/services/gameoflifeserviceimpl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../meta/services/gameoflifeservicemeta.cpp

    # Enums
    ${CMAKE_CURRENT_LIST_DIR}/../meta/golenumsmeta.cpp
)

set(JACK_MAKE_GENERATED_INCLUDE_DIRS_GOL ${CMAKE_CURRENT_LIST_DIR}/../..)